Macro Model/Controllers/ProdutoController.cs
using System.Diagnostics;
using System.Drawing;
using Macro_Model.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using static System.Net.Mime.MediaTypeNames;
using System.IO;
using System.Security.Claims;
using Microsoft.AspNetCore.Hosting;
using SixLabors.ImageSharp;


namespace Macro_Model.Controllers
{
	[Authorize]
	public class ProdutoController : Controller
	{
		private readonly AppDbContext _context;
		private readonly IWebHostEnvironment _env;
		public ProdutoController(AppDbContext context, IWebHostEnvironment env)
		{
			_context = context;
			_env = env;

		}



		public async Task<IActionResult> Lista(string ordenacao)
		{
			var usuarioNome = User.Identity.Name;
			if (string.IsNullOrEmpty(usuarioNome))
			{
				return RedirectToAction("Login");
			}

			var usuario = await _context.Cadastro
				.Include(c => c.Listadefavorito)
				.FirstOrDefaultAsync(c => c.Nome == usuarioNome);

			if (usuario == null)
			{
				return NotFound();
			}

			var produtos = _context.Produtos.AsQueryable();

			// Verifica se foi escolhida uma opção de ordenação
			switch (ordenacao)
			{
				case "Nome":
					produtos = produtos.OrderBy(p => p.Nome);
					break;
				case "Calorias":
                    produtos = produtos.OrderByDescending(p => p.Caloria);
					break;
				case "CaloriasMenor":
					produtos = produtos.OrderBy(p => p.Caloria);
					break;
				// Adicione mais casos conforme necessário
				default:
					produtos = produtos.OrderBy(p => p.Id); // Ordenação padrão
					break;
			}

			var viewModel = new ProdutoViewModel
			{
				Produtos = await produtos.ToListAsync(),
				ListasFavoritos = usuario.Listadefavorito.ToList(), // Convertendo HashSet para List
				OrdenacaoAtual = ordenacao
			};

			return View(viewModel);

		}




		public IActionResult Produto()
		{
			return View();
		}


        [HttpPost]
        public async Task<IActionResult> Produto(ProdutoViewModel model, IFormFile imagem)
        {


			if (ModelState.IsValid)
			{
				try
				{
					// Verifica se foi enviado um arquivo de imagem e se é válido
					if (imagem != null && imagem.Length > 0 && IsImagemValida(imagem))
					{
						Console.WriteLine("Imagem Ok ");
						// Define o caminho onde a imagem será salva
						var imagePath = Path.Combine(_env.WebRootPath, "imagens");

						// Verifica se o diretório existe, senão cria
						if (!Directory.Exists(imagePath))
						{
							Directory.CreateDirectory(imagePath);
						}

						// Define um nome único para o arquivo
						var fileName = Guid.NewGuid().ToString() + Path.GetExtension(imagem.FileName);

						// Define o caminho completo do arquivo
						var filePath = Path.Combine(imagePath, fileName);

						// Salva a imagem no diretório
						using (FileStream stream = new FileStream(filePath, FileMode.Create))
						{
							await imagem.CopyToAsync(stream);
						}

						// Atualiza o caminho da imagem no modelo
						model.Imagem = "/imagens/" + fileName;
					}

					// Converte ProdutoViewModel para Produto
					var produto = new Produto
					{
					
						Nome = model.Nome,
						Nutricional = model.Nutricional,
						Restricao = model.Restricao,
						Imagem = model.Imagem // Adiciona o caminho da imagem
					};

					// Adiciona o produto ao contexto e salva no banco de dados
					_context.Produtos.Add(produto);
					await _context.SaveChangesAsync();

					// Redireciona para a página de lista de produtos
					return RedirectToAction("Lista");
				}
				catch (IOException ex)
				{
					// Trata exceções de E/S (pode ocorrer ao salvar a imagem)
					ModelState.AddModelError("", "Erro de E/S ao salvar a imagem.");
				}
				catch (Exception ex)
				{
					// Trata outras exceções genéricas
					ModelState.AddModelError("", "Ocorreu um erro ao cadastrar o produto. Por favor, tente novamente.");
				}
			}

			//Se houver erros de validação ou se a imagem não for válida, retorna para a view com os erros
			return View(model);
		}

        // Verifica se o arquivo é uma imagem
        private bool IsImagemValida(IFormFile file)
        {
            // Lista de tipos de arquivo de imagem permitidos
            var tiposImagemPermitidos = new[] { "image/jpeg", "image/png", "image/gif" };

            // Verifica se o tipo de conteúdo do arquivo está na lista de tipos de imagem permitidos
            return tiposImagemPermitidos.Contains(file.ContentType);
        }




        public async Task<IActionResult> Editar(int? id)
		{

			if (id == null)
				return NotFound();

			var dados = await _context.Produtos.FindAsync(id);

			if (dados == null)
				return NotFound();
            var produtoViewModel = new ProdutoViewModel
            {
                Id = dados.Id,
                Nome = dados.Nome,
                Caloria = dados.Caloria,
                Nutricional = dados.Nutricional,
                Restricao = dados.Restricao,
                Imagem = dados.Imagem
            };
            return View(produtoViewModel);
        }

		[HttpPost]
		public async Task<IActionResult> Editar(int? id, ProdutoViewModel produtoViewModel, IFormFile imagem)
		{
            if (id != produtoViewModel.Id)
                return NotFound();
            if (id != produtoViewModel.Id)
                return NotFound();

            if (ModelState.IsValid)
            {
                var produto = await _context.Produtos.FindAsync(id);
                if (produto == null)
                    return NotFound();

                // Atualizar propriedades do produto
                produto.Nome = produtoViewModel.Nome;
                produto.Caloria = produtoViewModel.Caloria;
                produto.Nutricional = produtoViewModel.Nutricional;
                produto.Restricao = produtoViewModel.Restricao;

                // Manter a imagem atual se uma nova imagem não for fornecida
                if (imagem != null && imagem.Length > 0 && IsImagemValida(imagem))
                {
                    // Define o caminho onde a imagem será salva
                    var imagePath = Path.Combine(_env.WebRootPath, "imagens");

                    // Verifica se o diretório existe, senão cria
                    if (!Directory.Exists(imagePath))
                    {
                        Directory.CreateDirectory(imagePath);
                    }

                    // Define um nome único para o arquivo
                    var fileName = Guid.NewGuid().ToString() + Path.GetExtension(imagem.FileName);

                    // Define o caminho completo do arquivo
                    var filePath = Path.Combine(imagePath, fileName);

                    // Salva a imagem no diretório
                    using (FileStream stream = new FileStream(filePath, FileMode.Create))
                    {
                        await imagem.CopyToAsync(stream);
                    }

                    // Atualiza o caminho da imagem no modelo
                    produto.Imagem = "/imagens/" + fileName;
                }

                // Atualiza o produto no banco de dados
                _context.Produtos.Update(produto);
                await _context.SaveChangesAsync();

                // Redireciona para a página de lista de produtos
                return RedirectToAction("Lista");
            }

            return View(produtoViewModel);

        }


		public async Task<IActionResult> Detalhe(int? id)
		{
			if (id == null)
				return NotFound();

			var dados = await _context.Produtos.FindAsync(id);

			if (dados == null)
				return NotFound();

			return View(dados);

		}

		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null)
				return NotFound();

			var dados = await _context.Produtos.FindAsync(id);

			if (dados == null)
				return NotFound();

			return View(dados);

		}

		[HttpPost, ActionName("Delete")]
		public async Task<IActionResult> DeleteConfirmed(int? id)
		{
			if (id == null)
				return NotFound();

			var dados = await _context.Produtos.FindAsync(id);

			if (dados == null)
				return NotFound();

			_context.Produtos.Remove(dados);
			await _context.SaveChangesAsync();

			return RedirectToAction("Lista");

		}


		//[HttpPost]
		//public async Task<IActionResult> UploadImagem(IFormFile arquivo)
		//{
		//	if (arquivo == null || arquivo.Length == 0)
		//	{
		//		return BadRequest("Nenhum arquivo enviado.");
		//	}

		//	var extensao = Path.GetExtension(arquivo.FileName);
		//	var tipoConteudo = arquivo.ContentType;

		//	// Verificar se a extensão e o tipo de conteúdo correspondem a JPEG ou PNG
		//	if (extensao != ".jpg" && extensao != ".jpeg" && extensao != ".png")
		//	{
		//		return BadRequest("O arquivo deve ser do tipo JPEG ou PNG.");
		//	}

		//	// Salvar a imagem em uma pasta específica
		//	var nomeArquivo = Guid.NewGuid().ToString() + extensao;
		//	var caminhoArquivo = Path.Combine(_env.WebRootPath, "imagens", nomeArquivo);

		//	using (var stream = new FileStream(caminhoArquivo, FileMode.Create))
		//	{
		//		await arquivo.CopyToAsync(stream);
		//	}

		//	// Salvar informações da imagem no banco de dados, como caminho e tipo de conteúdo
		//	// Você pode associar essas informações ao seu objeto Produto

		//	return Ok(new { caminho = "/imagens/" + nomeArquivo }); // Retorna o caminho da imagem
		//}


        
    }
}

Macro Model/Views/Shared/_Layout.cshtml
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Macro Model</title>
    <link rel="stylesheet" href="~/css/_Layout.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Macro_Model.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css"/>
</head>
<body >
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="margin-left:15px">Macro Model</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse d-sm-inline-flex justify-contet-between" style="height:60px;">

                       

                    <ul class="navbar-nav mr-auto">
                        
                       
                        <li class="nav-item" style="width:120px">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cadastro" asp-action="Cadastro">Cadastre-se!</a>
                        </li>

                        @if (User.Identity.IsAuthenticated)
                        {
                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item" style="width:100px">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Cadastro" asp-action="Usuario">Usuários</a>
                                </li>
                            }

                            <li class="nav-item text-center " style="width:170px">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Produto" asp-action="Lista">Produtos e Alimentos</a>
                            </li>
                            <li class="nav-item" style="margin-left:10px">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Lista" asp-action="ListaFavoritos">Favoritos</a>
                            </li>

                        }
                    </ul>

                    <ul class="navbar-nav" style="display:flex;justify-content:right;width:100%;margin-right:15px">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                Bem vindo! @User.Identity.Name
                                <a class="nav-link text-dark btn btn-outline-secondary btn-sm py-1"  asp-controller="Cadastro" asp-action="Logout">Sair</a>

                            </li>
                        }
                        else
                        {

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Cadastro" asp-action="Login">Login</a>

                           
                            </li>
                        }



                    </ul>

                    @* <nav class="navbar navbar-light bg-light">



                    </br>
                   @*  <nav class="navbar navbar-light bg-light">

                        <form class="form-inline">
                            <input class="form-control mr-sm-0" type="search" placeholder="Pesquisar" aria-label="Pesquisar">
                            <button class="btn btn-outline-success my-0 my-sm-0" type="submit">Pesquisar</button>
                        </form>
                    </nav> *@
                </div>
                
    
            </div>
        </nav>
      
    </header>

    <div class="container" >
        <main class="bg-image"  role="main">
            	
            @RenderBody()
        </main>
    </div>

    


    <footer class="text-center position-fixed bottom-0 w-100 text-white footer-efeito" style="background-color:grey">
        <div class="text-center p-3">
            &copy; 2024 - Macro Model - <a class="text-dark" asp-area="" asp-controller="Home" asp-action="QuemSomos">Quem somos nós!</a>
        </div>
    </footer>
 

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Macro Model/Views/Shared/_ListasFavoritosPartial.cshtml
@model List<Macro_Model.Models.Listadefavorito>

@if (Model != null && Model.Any())
{
    <select class="form-control" name="listaId" required>
        <option value="" disabled selected>Favoritos</option>
        @foreach (var lista in Model)
        {
            <option value="@lista.Id">@lista.Nome</option>
        }
    </select>
}
else
{
    <select class="form-control" name="listaId" required>
        <option value="" disabled selected>Favoritos</option>
        <option disabled>Nenhuma lista encontrada</option>
    </select>
}